platform :ios, '7.0'

pod 'Parse', '~> 1.7'
pod 'ParseFacebookUtilsV4', '~> 1.7'
pod 'ParseUI', '~> 1.1.4'
pod 'SDWebImage', '~> 3.7'

pod 'MSCollectionViewCalendarLayout'
pod 'RestKit', '~> 0.22.0'
pod 'CupertinoYankee', '~> 0.1.0'
pod 'UIColor-HexString', '~> 1.0.0'
pod 'Masonry', '~> 0.4.0'
